-- tests/prose_waivers.lua — what the kit's US-English gate MUST NOT correct here.
--
-- Read by `tests/_kit/test_prose.lua` (localization-5). Per FILE and per WORD, never per file
-- alone: a whole-file waiver hides every OTHER British spelling in a file this repo edits often.
-- Every file below is waived for `minimis` and for nothing else, so a `colour` that lands in any
-- of them still reddens.
--
-- WHY `minimis` IS WAIVED, AND WHY IT IS TEMPORARY.
--
-- It is not prose. It is a SHIPPED IDENTIFIER, in four places at once:
--
--   * the header control's key -- `{ key = "minimise", ... }` (modules/HeaderControls.lua:127)
--   * the art name that key resolves to, through the same table
--   * the locale key `L["Show minimise"]` (locales/enUS.lua)
--   * and the SAVEDVARIABLES PATH `window.frame.minimised` (settings/Schema.lua:657,
--     defaults/Profile.lua:148), which every existing profile on disk is keyed by
--
-- Correcting the spelling is therefore a STORED-SHAPE CHANGE, not a spelling fix: it needs a
-- schemaVersion bump and an AceDB migrator that rewrites the path in every stored profile,
-- including the inactive ones, plus a locale-key move with every call site in the same change
-- (localization-1/2: a locale key IS the English source string, so renaming it orphans the key
-- silently). Done carelessly it loses every player's collapsed-window state.
--
-- So this waiver is a DEBT, not a decision, and it is written here rather than in a commit
-- message so the next sweep finds the reason instead of re-fixing it. The migration is owed;
-- when it lands, every entry below comes out in the same change.

return {
    waived = {
        ["README.md"] = { minimis = true },
        ["core/Diagnostics.lua"] = { minimis = true },
        ["defaults/Profile.lua"] = { minimis = true },
        ["docs/module-map.md"] = { minimis = true },
        ["docs/schema.md"] = { minimis = true },
        ["docs/settings-panel.md"] = { minimis = true },
        ["docs/smoke-tests.md"] = { minimis = true },
        ["docs/superpowers/plans/2026-08-27-settings-redesign.md"] = { minimis = true },
        ["docs/superpowers/specs/2026-08-23-header-controls-design.md"] = { minimis = true },
        ["docs/superpowers/specs/2026-08-27-settings-redesign-design.md"] = { minimis = true },
        ["docs/testing.md"] = { minimis = true },
        ["locales/enUS.lua"] = { minimis = true },
        ["modules/HeaderControls.lua"] = { minimis = true },
        ["modules/Window.lua"] = { minimis = true },
        ["modules/Window_Header.lua"] = { minimis = true },
        ["modules/Window_Placement.lua"] = { minimis = true },
        ["settings/Schema.lua"] = { minimis = true },
        ["settings/Schema_Paths.lua"] = { minimis = true },
        ["tests/test_diagnostics_deathrecap.lua"] = { minimis = true },
        ["tests/test_headercontrols.lua"] = { minimis = true },
        ["tests/test_mediasetup.lua"] = { minimis = true },
        ["tests/test_schema.lua"] = { minimis = true },
        ["tests/test_window_header.lua"] = { minimis = true },
        ["tests/test_window_placement.lua"] = { minimis = true },
        -- The GENERATED inventory, which carries the test names verbatim and therefore carries
        -- the identifier with them. It is regenerated by the runner, never edited, so it clears
        -- itself when the migration above lands.
        ["docs/test-cases.md"] = { minimis = true },
    },
}
